name: Deploy docs

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/mkdocs-deploy.ya?ml"
      - "mkdocs.ya?ml"
      - "poetry.lock"
      - "pyproject.toml"
      - "docs/**"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'
          cache: 'poetry'

      - name: Install Poetry
        run: pipx install poetry

      - name: Install Dependencies
        run: poetry install --no-root

      - name: Deploy website
        run: poetry run mkdocs gh-deploy
